# MCU name
MCU = atmega32u4

# Bootloader selection
BOOTLOADER = atmel-dfu

# Build Options
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
NKRO_ENABLED = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
RGB_MATRIX_ENABLED = yes
RGB_MATRIX_DRIVER = WS2812
OLED_ENABLE = yes
LTO_ENABLE = yes
